### ISSUE TITLE
BS SD (EA for FPT_BDP_EXT.1)

### ISSUE THREAD

**Issue by The-Fiona** [biometricITC/cPP-biometrics#106]
The statement "However, the evaluator shall examine that the TOE processes any plaintext biometric data except publicly accessible biometric data (e.g. face image) within the security boundary of the SEE." is causing me to ask a question:

How do we define what is publicly accessible biometric data ?
When I go out in public usually my face is available for all to see, but I also leave my fingerprints, and samples of DNA around (sorry for that thought!).  I also understand that fingerprints may be "readable" by cameras nowadays, and have read some articles on long-range iris-scanning.
So, assuming that this individual does go out in public, is there any biometric data that is not publicly available?

So, in this EA I guess we either need to precise "publicly accessible biometric data" or remove the exception - Which would effectively mean that we ask for all biometric data to be stored in the SEE.

Welcoming comments on this matter :)

**Comment by woodbe** [comment]
@n-kai 

So generally when a sensor will be used for authentication (especially for MDF-targeted devices) the sensor will be incorporated into the boundary of (for lack of a better descriptive term) the Dedicated Security Components (DSC). So in the case of a Samsung device, the fingerprint sensor has a dedicated path to the TEE and cannot be accessed by the Rich OS. Generally all authentication mechanisms would be targeted in this way so that the core logic/processing would occur in the SEE (whatever that is), whether it is a password or biometric being used to authenticate the user. 

So for something like a front-facing camera which may be configured to be able to be used both as an authentication sensor and as a selfie camera, the camera would normally be plugged into the DSC boundary, but have the option that if it is not being used for authentication purposes to allow an application to request access to the image produced by the camera. This is what I would expect, anyway. I have not looked into this specifically on Samsung devices or Android in general as we have not tried to validate the face unlock function (we have limited ourselves to fingerprint and iris to date).

To that end though, if the sensor has the ability to be used by the Rich OS and the SEE, it must support some sort of priority-based exclusive access lock so that if the sensor is being used for an authentication operation by the SEE that nothing else can gain access until that operation is completed (and probably for some sort period right after to prevent say taking the picture of a face right after successful authentication since that would be a great time to grab the image).

**Comment by n-kai** [comment]
@The-Fiona @woodbe @BrJu 
Thanks for your input. I agree with the proposal from @BrJu in #85 to remove "except publicaly accessible biometric data" from the requirement.

**Comment by n-kai** [comment]
We agree to remove "publicaly accessible biometric data". Naruki will create a pull request for this change.

**Comment by BrJu** [comment]
will be cover by #85 
Please @The-Fiona confirm that you agree to close the issue

**Comment by The-Fiona** [comment]
I agree :)
