### ISSUE TITLE
Linking requirements between PPs

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#107]
It was pointed out during the CCUF meeting that there is not a well defined way to link requirements between PPs in an enforceable way. This came up specifically related to the Hybrid requirements, with a comment that maybe this should be in the MDF (one of the edits there).

One possible answer (though I do not know the specifics as I have not looked into them) is making the cPP for use case 1 into a PP-Module or even a Package. These do not impact what we need to come up with (I think), but we should investigate the linkage and if necessary whether this should be something other than a cPP for use case 1.

**Comment by BrJu** [comment]
also related to #117  -- low priority

**Comment by woodbe** [comment]
Since it seems that v1 of our output will be a cPP (as opposed to a PP-Module), we could close this.

**Comment by n-kai** [comment]
I changed my thought. Biometrics cPP should be the PP moulde for MDFPP (BasePP) because it requires that mobile device is evaluated against the MDFPP and the form of PP moudue is easier to express this requirement. 

However, if the CCRA can't recognize the cPP module, we have to convert the module into cPP again. But the conversion doesn't take much time.

**Comment by woodbe** [comment]
Closed based on moving to a cPP Module
