### ISSUE TITLE
EAL?

### ISSUE THREAD

**Issue by nils-tekampe** [biometricITC/cPP-biometrics#131]
Hi all,
I took the time to read once again thru our whole PP Today evening and have identified one issue for me. Maybe it's just too warm here here too get this clear but I'm trying bring it to the point:

Our PP has no EAL. However, I'm pretty sure to remember that we agreed during a call or a discussion in some issue that we would primarily stick to the default assurance components from part III of CC and would give our PP an assurance level. Our SD would then provide additional information/interpretation for these requirements. 

I'm remembering this pretty clearly because - from the German perspective - this has been a very essential point. But after we agreed on this (well, I thought we did) I did not follow this part of the PP any longer really closely. 

Can anybody here please refresh my memories on this aspect? That would be highly appreciated. 

Beside this point, I only found minor things during my review that I can put into a separate PR.

**Comment by n-kai** [comment]
@nils-tekampe 
I am not sure if my comment is right answer to your question but MDFPP and other published cPP (See https://www.commoncriteriaportal.org/pps/?cpp=1) identify the following security assurance components.

ASE_CCL.1, ASE_ECD.1, ASE_INT.1, ASE_OBJ.1, ASE_REQ.1, ASE_SPD.1, ASE_TSS.1
ADV_FSP.1, AGD_OPE.1, AGD_PRE.1, ALC_CMC.1, ALC_CMS.1, ATE_IND.1, AVA_VAN.1

This is equivalent to the EAL1+ (ASE_SPD.1).

Current BiocPP identifies EAL1+(ASE_SPD.1+ASE_OBJ.2+ASE_REQ.2). 

Difference between ASE_OBJ.1/2 and ASE_REQ.1/2 is; 
ASE_OBJ.1 only requires to describe the security objectives for the operational environment, however, ASE_OBJ.2 requires to describe the security objectives for the TOE and operational environment and security objective rationale.
ASE_REQ.2 requires to demonstrate that the SFRs meet all security objectives for the TOE and explain why the SARs were chosen, in addition to the ASE_REQ.1 requirements.

The reason why the BiocPP selects ASE_OBJ.2 and ASE_REQ.2 is as follows.
ASE_OBJ.2: MDFPP describes security objectives for TOE and security objective rational (so MDFPP should also identify ASE_OBJ.2, instead of ASE_OBJ.1). BiocPP follows this structure because it's intended to be used with MDFPP.
ASE_REQ.2: Current published cPP describes "SFR Rationale" that explains the mapping between threats/OSP and SFRs. BiocPP also follows this but BiocPP explain the mapping between security objectives and SFRs because BiocPP selects ASE_OBJ.2 and defines security objectives for the TOE.

We can explicitly states that this cPP requires EAL1+(ASE_SPD.1+ASE_OBJ.2+ASE_REQ.2) for the TOE evaluation in "7. Security Assurance Requirements". Is this what you want to see in the cPP?

We can also downgrade BiocPP requirements to EAL1+(ASE_SPD.1) to follow the MDFPP and other cPPs.

**Comment by nils-tekampe** [comment]
@n-kai Thank you so much for your message. This is a relieve.
Yes, I think it would be a great idea, if we could call it EAL 1+. 

The other aspect is that the descriptions say that some of the assurance classes can be omitted. e.g. it says: 

>  Therefore, AGD_PRE.1.1D is implicitly already done by those evaluation and no additional documentation is necessary.

I would suggest to slightly redraft these paragraphs as well. If we are targeting for EAL1, the documentation is required but it may be the same documentation that has already been used in the context of the MDFPP evaluation. What do you think?

If you could just le me know whether this is OK for you, then I will prepare a PR with the necessary changes.

**Comment by n-kai** [comment]
@nils-tekampe 
No problem, it's OK for me.  Thank you for preparing the PR.

**Comment by nils-tekampe** [comment]
@n-kai great to hear! Thanks!
I just created the PR.

**Comment by nils-tekampe** [comment]
Closed as PR #132 is about to be merged.
