### ISSUE TITLE
Extended component definitions should be referenced and not replicated

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#171]
From @ohenniger :

The contents of "7.3 Identification and Authentication (FIA)" is redundant to the extended-component definitions "12.1 Identification and Authentication".

The extended components should be defined in 12.1 and should be referenced, not replicated, in 7.3. 

---

The contents of "7.4 Protection of the TSF (FPT)" is redundant to the extended-component definitions "12.2 Protection of the TSF (FPT)".

The extended components should be defined in 12.2 and should be referenced, not replicated, in 7.4.

**Comment by woodbe** [comment]
@ohenniger I am not sure I understand the difference here between replication and reference. Do you mean that the application notes should be left to section 12.x or something else?

**Comment by woodbe** [comment]
An interesting question that occurred to me on this topic is that we have the same application notes in both places and they are numbered separately (i.e. note 12 and note 26 are the same because they are both for FIA_MBE_EXT.1.1). Maybe this is the point about replication?

**Comment by The-Fiona** [comment]
I am not understanding this issue well.
7.3 and 7.4 are referencing the extended components defined in 12.1 correctly.

I agree about the application notes as a possible cause of this issue. However, if you consider that the point of clause 12 is to define the extended components just as they would be if they appeared in the part 2 components catalogue. Part 2 contains "generic" application notes in part 2 Annex "A".
These Annex "A" application notes are rarely copied into an ST/PP/PP-Module or package that uses them (but they are still applicable). However we do see additional Application notes in these documents, that are specific to the case at hand.

So for the case of an Extended components, defined in section 12, I would recommend to add any **very generic** application notes to the definition there, and when instantiating that component in clause 7, add any specific notes there.  

In practice, when folks get to writing an ST, they will likely focus on clause 7 rather than clause 12.

**Comment by woodbe** [comment]
Response form @ohenniger 

Redundancy comes with the risk of inconsistency. Therefore, I think the contents of 7.3 could be replaced with “The TOE shall meet the requirements FIA_MBE_EXT.1.1, FIA_MBE_EXT.2.1, FIA_MBV_EXT.1.1, FIA_MBV_EXT.1.2, FIA_MBV_EXT.2.1, and FIA_MBV_EXT.3.1, which are defined in 12.1”. By the way, why is FIA_MBE_EXT.3.1, which is defined in 12.1.1, not mentioned in 7.3?

**Comment by The-Fiona** [comment]
Thank you @ohenniger. Now I understand the issue.

While we agree that at first sight this seems like a redundancy,  as I explained above, the section 12 is creating the formal definition of the components, and could contain uncompleted components. Section 12 provides the dependencies and hierarchical information for these new components, and is required to do so in the same format as the CC part 2. One could think of Section 12 as an extension of CC part 2.

Section 7 of our document must appropriately "complete" the extended components defined in Section 12. in the same way that components are completed from the part 2 catalogue. In a PP (or PP-Module) completion of the component depends on the requirements of the authors. In an ST all of the components must be completed. (An example of a component with allowed operations is In our document is FIA_MBV_EXT.1.1 )

If we do not follow the convention given in CC, then evaluations of documents containing the PP-Module will fail. (For example a PP-Configuration (CC Part 3, ACE) or an ST (CC Part 3, ASE). When these documents are evaluated any inadvertent inconsistencies will be identified and fixed.

The issue identified with the application notes is valid, and @woodbe will create a separate issue to track resolution of this.
