### ISSUE TITLE
AVA_VAN & ATE_IND consistent descriptions

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#181]
As reported by Mary Baisch, the toolbox and the SD are inconsistent in the descriptions of AVA_VAN. Section 6 defines AVA_VAN using the toolbox, but according to the toolbox description we have explicitly stated that it only covers ATE_IND. I have made an [update](https://github.com/biometricITC/cPP-toolboxes/pull/13) proposed for the toolbox about adjusting it so it is clear that the toolbox is for ATE_IND but could be used as the basis for AVA_VAN, but that it is not covered in the toolbox.

Looking at section 6.3, it seems this is really the procedure that should be followed for ATE_IND, that the evaluator probably needs to check for updated PAI beyond that already laid out in the toolbox. I'm not really sure how to handle that, but it would seem that the toolbox is what we know at the time it is published/updated. Since new things could be added at any time (based on external research), should the ATE_IND assume these should be included (within some reason) or is this really AVA_VAN?

I think a lot of the AVA_VAN that talks about creating the test plan is good, but I am not sure about the rest.

**Comment by woodbe** [comment]
I want to add one thing to this discussion that was pointed out (copying directly here from Mary):

> Note:  If this is made into a cPP, then the AVA_VAN section would need to be redone, since the module currently relies on the MDFPP to express the baseline AVA_VAN (vanilla CC SAR), and then adds the search for PAIs. I would imagine the iTC would adopt the approach the other iTCs took - the four types of hypotheses, etc. That's going to be a lot more work.

Of course this is a lot of what we have talked about for the inclusion of AVA_VAN (or not), especially if this is an independent cPP, and I do not know that the group is sufficiently equipped to do this. I completely agree with her point, but I also do not think we have the expertise or people to go this route.

**Comment by n-kai** [comment]
>should the ATE_IND assume these should be included (within some reason) or is this really AVA_VAN?

I assume that the following toolbox update process.
1. evaluator finds the new PAI during AVA_VAN that is not included in the toolbox and evaluator determines that it should be tested. ([SD] 6.3.1.2.2)
2. evaluator creates a test item for the new PAI at the same format and level of detail as existing ones in Toolbox and report it to the BIO-iTC ([SD] 6.3.1.3.2)
3. BIO-iTC determine it should be added to the toolbox or not and update the toolbox if all member of the iTC agree.

I think that there is quite low probability that the evaluator can find the completely new PAI because, for example, researchers have been creating 2D face PAIs using only printout, photo or video and no new type of PAI has been invented for long time. So most of "new PAI" are not completely new and can be handled by the toolbox with some modification.

>but I also do not think we have the expertise or people to go this route

I think that our iTC should consider only one hypotheses that is the presentation attack (attack surface is limited to the interface to the biometric verification and any other attacks are supposed to be blocked by the mobile device) So we have to explain how the toolbox is created or cover existing all type of PAIs based on the three types of hypotheses (I exclude "Type 3 Hypotheses –Evaluation Team Generated") but I think that it is not difficult job if we can create good toolboxes for the target modalities.

**Comment by The-Fiona** [comment]
This may be over simplistic but...
If it is a PP-Module, then yes it inherits AVA_VAN from it's base PP (eg MDFPP)
If it is a cPP then, yes, we have to write AVA_VAN. Perhaps in the first edition we simply cut and paste the AVA_VAN from MDFPP into the biometrics cPP. Of course that would be a very NIAP-centric solution. For the next editions we can think more about the various hypotheses scenarios.

In any case, I agree that the iTC should start with only the presentation attacks described above. Pedantically, I would suggest (in the case of a cPP module)  that "and any other attacks are supposed to be blocked by the mobile device" should be "and any other attacks are assumed to be mitigated by the base-PP"

**Comment by The-Fiona** [comment]
Naruki-san,
Yes, I like your toolbox update process. It should be similar to the interpretations team and could use that process (which we also need to develop). We could have biometric interpretations ("BITS") c.f. the NITS for the network devices iTC. :)

I thought we already had an issue for that, but I don't see it there.

**Comment by woodbe** [comment]
Closing as this is no longer current
