### ISSUE TITLE
Add the term 'plaintext biometric' in glossary

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#214]
Plaintext is a term used in cryptography that refers to a message before encryption or after decryption. That is, it is a message in a form that is easily readable by humans

Issue 16 from Cybersecurity Malaysia

**Comment by n-kai** [comment]
In 8.3.1 term "plaintext biometric data" is used and "biometric data" is defined in 2.5. Glossary so I don't think that adding "plaintext biometric data" to 2.5 is unnecessary because base-PP (MDFPP) also uses term "plaintext" without definiton in Glossary so PP-module should follow the way of definition of its base PP

**Comment by woodbe** [comment]
based on 1/30 call this will be closed as the group agrees this isn't necessary
