### ISSUE TITLE
Template vs Sample Quality

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#235]
[Section 2.3.2](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_ea_for_fia_mbe_ext_2) of Supporting Document talks about the quality of the template, but I believe is actually referring to the quality of the sample encoded within the template. Presumably, the template is a valid parsable file, or corrupt. Also, presumably, templates are compared to another template, not a sample. Suggest specifying to what the quality refers throughout.

**Comment by n-kai** [comment]
Yes I agree. In case of finger vein recognition, if the sample doesn't have vein patterns clear enough, the TOE has to repeat data captures until the TOE can get clear vein pattern to create a template that have enough features for comparison.

I propose the following change.

**Biometric verification performance depends on quality of samples from which templates are generated. The evaluator shall examine that the TOE checks the quality of samples to create enrolment and authentication templates based on the assessment criteria so that the TOE can verify a user with an adequate reliability.** 

If above change proposal is accepted, I will check other part of SD to keep consistency
