### ISSUE TITLE
ATE_IND Strategy, Temp Files and Volatile Memory

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#237]
[Section 2.4.3.5.2](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_strategy_for_ate_ind_4) of Supporting Document: Suggest some additional steps in this check. Current steps discount temporary files and the contents of volatile memory. Suggest something that can dump the contents of volatile memory before/after and knows the format of biometric data files to ensure data didn't stick around in uncleared volatile memory. Also suggest live-monitoring of the file system instead of a before/after operation diff, as it may be possible to recover a removed temporary file.

**Comment by n-kai** [comment]
I agree but I want to avoid duplicate evaluation effort between BIO PP module and its base PP (MDFPP or GPOS PP). For example, MDFPP requires to separate privileged domain from user domain (FPT_AEX_EXT.4). If the evaluator can verify that the mobile device doesn't allow user app to access any privileged data including privileged temp file or volatile memory during the mobile device evaluation based on MDFPP, simple check as described in 2.4.3.5.2 may be enough (2.4.3.5.2 is created based on evaluation activity of FPT_AEX_EXT.4 so that the evaluator can perform 2.4.3.5.2 with evaluation of FPT_AEX_EXT.4 at once). But this is not the case, especially I don't know what evaluation is performed for GPOS PP, I will update 2.4.3.5.2 as proposed by @gfiumara so I need input from other members who have experience of evaluation based on MDFPP and GPOS PP on this topic. But if I have no input, I will simply add @gfiumara proposal.

**Comment by woodbe** [comment]
I am not sure exactly how biometric systems work on a Windows (or other) system. I would assume that the templates and such are handled in some restricted area, not in the rich OS, so I do not know how you would readily be able to do the scanning or monitoring of the system to see. I will try to reach out to Microsoft and see if they can provide some information.

**Comment by n-kai** [comment]
I think that there are live-monitoring or disk analysis or forensic tools for windows that can identify any files that newly created, updated or removed. The evaluator can use such tools to find new or update files including temporary ones during biometric verification. 
I also believe that there are memory analysis tool that identify which process updates which memory address but it may be time consuming to analyze such activities. So I allow developer to identify codes that actually encrypt the data and evaluators to confirm or test that the code actually do the right thing with support from developer. I can add such text to the SD.

**Comment by woodbe** [comment]
I have reached out to Microsoft. The short answer though is that it is up to the biometric vendor what they do as far as securing the data, so it could be contained within the sensor system or it could be in the normal file system (or maybe somewhere else based on what is available). 

My thinking here is that if the sensor drops its stuff into the file system that it doesn't meet our requirements for certification because it isn't protecting the data sufficiently. This may actually relate to #210, I'm not sure.

My thinking is that our expectation is that this information is NOT being stored in a location that would allow for this type of testing, so what we end up with is that any biometric system that would be subject to this in a GPOS environment would fail in our requirement that the data be in an SEE.

So my inclination, if anything, would be to strengthen the wording around the SEE expectation (I don't have something for this off hand), but I would not add anything else.

**Comment by n-kai** [comment]
Level or effort of testing required by PP module should be same as one required by Base PP because assurance level of PP module should be inherited from Base PP. This means that if the base PP evaluation doesn't require evaluator to use live file or memory monitoring, our SD should also follow it (but our SD should ask developers to give more information about how they protect biometric data using SEE) but if the base PP asks evaluator to use live file or memory monitoring, our SD also should ask evaluator to test that biometric data is protected in the same way using live monitoring tool.

**Comment by woodbe** [comment]
Based on comments from @The-Fiona look at the PP-Config for MDF (and GPOS) about making sure that the biometric data would be included in any sensitive data searching that is performed (i.e. FPT_AEX_EXT type tests).

**Comment by woodbe** [comment]
After looking at this specifically for the MDF, I realized it is FCS_CKM_EXT.4 that is what we are looking for. the FPT_AEX_EXT.4 is about kernel vs user space and does not deal with a TEE (or similar). I have created a pull request adding a line about this in the PP-Config.
