### ISSUE TITLE
Mandate Demographic Diversity

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#241]
[Section 7.3.2 Item a](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_target_application_and_influential_factors) of Supporting Document: Demographics play a **huge** role in modalities like face, with some 2D image algorithms performing upwards of 100x different than others on certain populations. It is likely no longer fair to publish a FAR/FRR number without specifying the demographic breakdown of such a value. Although live subject data collection is time consuming, expensive and difficult, highly suggest **requiring** (not _recommending_) a certain larger mix of demographics, and/or be required to report on individual groups separately to the same statistical significances described elsewhere. One TOE's FMR against all Caucasian 50 year old males is not comparable to another TOE's FMR of African American females is not comparable to an FMR of a "diverse" 18-21 crowd.

**Comment by n-kai** [comment]
I agree with you. Japanese vendor normally use their employees (many of them are 30-50 and men) to measure FAR/FRR and they know that different value of FAR/FRR can be measured by 20-30 women. 7.3.2 Item a should be copied into the final validation report so that everyone can look at.

**Comment by woodbe** [comment]
I have two questions about this. I completely agree with the point, but have 1 concern and 1 suggestion.

The concern is whether this becomes a hidden requirement. If the vendor is doing testing that meets requirements similar to what FIDO specifies for 1:10K FAR for fingerprint, they would have to have roughly 125 people with 2 fingers, so what if that was 80% Japanese men between 30-50 and this was reported as such. Would this mean they fail?

Basically what I'm concerned about here is what is considered a sufficient demographic mix, and where is that defined? Saying these numbers don't work is one thing, but what is considered acceptable such that any lab would come to the same conclusion about it being acceptable. I don't know how to define that clearly. Also, is this something we document in the SD or in the Toolbox?

Now the suggestion is that we provide a standardized format for the demographic data that should be reported. If we don't, then the vendor may leave something out, and we should be clear about at least the type of data that needs to be reported, regardless of the requirements about what we want that data to look like.

**Comment by n-kai** [comment]
_so what if that was 80% Japanese men between 30-50 and this was reported as such. Would this mean they fail?_
No, the SD requires 1) developers to report demographic info (i.e. age, gender and ethnic origin) in the performance test document and 2) evaluator to check the required info is actually described in the test document. 

We discussed this issue with Japanese vendors in the past. They said that ISO/IEC 19795-1 doesn't require to conduct performance testing using "sufficient demographic mix" because it's difficult to gather large number of such test subjects (Japanese vendors gather several thousands of test subjects for performance testing and it's impractical gather such "sufficient demographic mix". But ISO/IEC 19795-1 only requires to report test demographic info in the test report. So the current SD follows ISO/IEC 19795-1 and only require the developers to report demographic info in the test document.

_standardized format for the demographic data that should be reported_
It may be difficult  to determine such format. Currently this PP-module is intended be used GPOS and MDFPP so target population can be standardized considering demographic of all PC/mobile users worldwide however if our PP-module is used for game machine, target population may be largely different from ones for  PC/mobile users.  

I think that developer themselves should define demographic mix to be used for testing taking a balance between similarity between target population and test demographic mix and cost to gather such demographic mix.

**Comment by woodbe** [comment]
@n-kai 
What I meant by a standardized format is a blank table that would show the information we would expect to be reported, not to create some new standard. For example, maybe we want to see the following information always reported:

- ethnicity
- age ranges
- gender

So would it be sufficient to just show what the ethnicities are, or do we want to know the numbers associated with each (percentages, maybe)?

My point here is that if we are asking for them to report on the information, we should guide them to what level of information we expect to see, not what the information contains. 

I would be looking for something that this:

ethnicity            Japanese   50%              Caucasian    30%               Indian     20%
Age range         18-25  5%                      26-35  30%                        36-45   40%                46+   25%
Gender              Male   47%                    Female    48%                    Other    5%

I don't know if we feel there is a need for breakdowns within these numbers (for example Japanese women in the 36-45 years old category). But either way, this is what I am trying to get to. If this is the minimum that is acceptable, then we specify that. If someone wants to give more, then great, but if they want to give less, then if we don't specify what we think is required, how can we say if it is not enough?

**Comment by gfiumara** [comment]
I think showing the breakdown as @woodbe suggests is a good first step for full disclosure. Actual numbers can be derived from percentages since number of subjects is reported.

> what is considered a sufficient demographic mix

It's hard to pin down, especially considering these are live tests with different subjects and different samples every time. An algorithm developer should be attempting to find such mixes to choose their fixed threshold such that false positives remain approximately equal, regardless of the mix chosen (100% 20-30 European males == 100% 80-90 AA females == whatever combination you can dream). I don't know that this document can (or should) choose a mix, but instead encourage equal false accept.

> I don't know if we feel there is a need for breakdowns within these numbers

In a perfect world, it would be good to encourage different breakdowns of subjects. I can see not requiring this for feasibility's sake, but to at least *encourage* it for the plethora of reasoning described in [NISTIR 8280](https://doi.org/10.6028/NIST.IR.8280).

**Comment by n-kai** [comment]
We can propose the standardized format based on NISTIR 8280 (I went though ISO document to look for such format but I could find it in ISO) and ask developers report demographics based on the format with number of total test subject.

1. Country of birth
Developer has to categorize country of birth of test subjects into following region and report percentage of subjects in each region.

- Eastern Europe - Russia, Poland and Ukraine etc
- Central America - Mexico, Honduras, El Salvador, Nicaragua etc
- West Africa - Ghana, Liberia, Nigeria etc
- The Caribbean - Haiti, Jamaica etc
- East Africa - Ethiopia, Kenya, Somalia etc
- South Asia - India, Iran, Iraq, Pakistan etc
- East Asia - China, Japan, Korea, Philippines, Thailand, Vietnam etc

2. Age group
Age distribution should be reported by the intervals (00−20], (20−35], (35−50],(50−65], and (65−99]

3. gender
Ratio of male and female

**Comment by woodbe** [comment]
I started to go through with updating the BIOSD and realized that the breakdown shown here is more based on a study and misses several regions that I'm not exactly sure how to break down (since there are similarities):

* Western Europe (everything West of Poland, roughly + Scandinavia)
* North America
* South America
* Australia
* South Pacific

What I'm not sure of here is if Western Europe/North America/Australia should be one?

South America could be with Central America, maybe?

Also, since this is listed as country of birth, at least in the US, there is a lot of range of ethnicities, so it may be best to leave it with that instead of country of birth, since maybe more than others, saying you are born in the US doesn't mean quite as much (UK may be similar to some extent with the Indian population).

Thoughts?

**Comment by n-kai** [comment]
You can break down countries based on UN country grouping.
https://www.internetworldstats.com/list1.htm#geo

I also thought that the ethnicity was better information to categorize test subjects than country of birth, however I heard that some people don't want to reveal their own ethnicity for privacy reason and there is no internationally accepted criteria to define and categorize population into each ethnicity (See https://unstats.un.org/unsd/demographic/sconcerns/popchar/popcharmethods.htm#E)

So we can update BIOSD like follows
1. developer has to categorize test subject into UN country grouping at least
2. developer may categorize test subject into ethnicity. However such ethnicity shall be defined in nation's census and developer shall determine ethnicity following such definition.
