### ISSUE TITLE
his/her vs their

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#264]
Reading through the PP-Module I see many places (probably most) that use "his/her" and a few that use "their" when discussing what to do (i.e. the user would use his/her biometric).

I want this to be consistent, so the question is what should we use. I see three options:

- his/her
- her/his
- their

I personally usually prefer their as it is neutral and I think reads easier (and maybe today with gender fluidity maybe less fraught, but that is just me putting it out there).

I will make the change if we can agree about which one to use.

The other option would be to try to rewrite any sentence to remove the need for the pronouns. This would be possible, I think, but would be a lot more work. My main goal in this is to just be consistent, but not cause any potential concerns with how the documents read outside the iTC.

**Comment by n-kai** [comment]
I am not a native English speaker so I will fully agree with any choice you make.

**Comment by The-Fiona** [comment]
I agree that being non gender specific is the way to go.

1. In general we should try to rephrase so that we avoid completely the problem.
2. "They/Their" can work, but is plural and could end up being misinterpreted.
3. Another method is to repeat the noun, IMHO can be messy. 
"The User ate his lunch" := "The User ate the User's lunch" (Note in this example using "their" would change the meaning of the sentence.)

**Comment by The-Fiona** [comment]
Also, using "his/her", "her/his", or even "their" does not include other genders with which folks identify.
