### ISSUE TITLE
Attack Potential (again) for eye

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#273]
As I was going back through the BIOSD and CEM to update the eye toolbox properly, I realized that for the eye, all the tests, by how we have defined the attack calculations generally, end up being at least a 12 (Enhanced-Basic) and some at 16 (Medium).

We have defined in the BIOSD that iris (or eye) should be considered a difficult modality to get, which gives it 8 points on its own. We have also seemed to standardize on moderate for the window of opportunity to the TOE, which is 4 points.

Check out the NIR attack (which has 16):
https://github.com/biometricITC/Eye-Toolbox/blob/master/attacks/04_01-Eye-attack.adoc

That said, I basically agree with these numbers, to actually try to get past a biometric I expect the attacker would need to have access for a bit of time, so moderate seems right, and the eye requirements are definitely harder to meet than others (especially the NIR ones), since you need high resolution, bright light (to show the iris) and a clear line of sight to the eye from straight ahead. 

Since we have claimed overall we are targeting Basic, that means according to the CEM we need below 10 points.

So my question is does this mean that for iris (and maybe vein since that is also marked as difficult for window of opportunity) that they test to resist Enhanced-Basic instead of Basic? I have not looked fully though the BIOSD about what this would mean., but I'm not exactly sure how this should proceed since we had agreed to a Basic attack potential as what we were targeting.

**Comment by n-kai** [comment]
_So my question is does this mean that for iris (and maybe vein since that is also marked as difficult for window of opportunity) that they test to resist Enhanced-Basic instead of Basic?_

I am trying to create tests for vein that are within Basic. Like face, we can take a high resolution photo of palm or finger, then enhance blue/green in the image with photo editing software to extract vein pattern as much as possible , and then print the pattern on the paper to make vein artifacts. I am not sure I can make it or not but I need more time to think about this. 

I don't know the same approach can be taken to eye artifacts but we can adjust the table to fit our needs if we can't make good toolboxes based on the current table.

**Comment by woodbe** [comment]
I don't see though how to get iris down below 10 unless we say that it is not difficult but moderate Window of Opportunity to get the iris (which I don't think is right, I do think that one is difficult), and that is 8 points right there. I am not sure that realistically we can define vein or eye) to be only moderate difficulty. 

Would we really have a problem if we left it to the modality to determine what level it resists? Or specify some set of tests, and their associated APs and then let the vendor specify the level they resist (with the minimum being Basic, but that they could choose higher on modalities where there are tests for Enhanced Basic)? We still have the limits on time being a week, so even Enhanced Basic would have bounds, but I don't know what other problems this could cause, I just don't see how we could do any testing in this case, since with nothing else, if the Access to the TOE is a 4 for everything (which makes sense), and Access to Biometrics is Difficult at 8, you cannot be lower than 10 in any way, not matter how easy the attack itself is.

**Comment by woodbe** [comment]
Based on the changes in #272 and #274, this is being closed
