### ISSUE TITLE
[cPP CHANGE] 

### ISSUE THREAD

**Issue by ccolin318** [biometricITC/cPP-biometrics#282]
**What is the change request for the cPP/PP-module? Please describe.**
A clear and concise description of what the change is. This could be a problem with the existing document or just a new request

Comment from MITRE's review: 
"Only one threat is defined; T.Casual_Attack which is defined as   a "zero-effort imposter attempt".

More deliberate attacks are within the realm of possibility and should be considered for   documentation.  The presence of the SFR "FIA_MBV_EXT.3 Presentation attack detection for biometric verification" indicates that these possibilities have been considered. 

Consider an additional threat to be included in section 6.1: T.Intentional_Attack An attacker may attempt to impersonate as a legitimate user without being enroled in the TOE. In order to perform the attack, the attacker attempts to mimic or spoof a legitimate users biometric characteristic."

**Comment by woodbe** [comment]
So we specifically have T.Casual_Attack, and not any sort of intentional attack, though I can't find anything specific in the notes for it, but it basically comes down to these:

- Without requiring PAD testing (which this PP-Module does not), it is tough to say that there is much you could do beyond the casual attack to bypass authentication if you are limited solely to your own biometric (i.e. you own finger)
- We are claiming the same AVA_VAN as the base PP, which in this case is AVA_VAN.1, and only at Basic Attack Potential, when PAD is being used. There isn't much left, given the bounds of the subsystem within a larger device (i.e. a mobile device as of right now) that is likely to be covered specifically by the biometric system as opposed to the broader device. Things which may attack the broader device would not be considered in scope here, but would be covered by the base PP requirements.

The way the proposed (rough) text is written, this is basically a threat for PAD (mimic or spoof), and the problem we run into there is having an "optional" threat. This isn't something really handled well at this point (at least that I have seen), and we discussed it when we made PAD optional, but couldn't come up with a way to actually handle it in the PP-Module.

Lastly, as the first iteration, I would like to follow a "crawl, walk, run" method of building up the requirements, and based on the above, I'm not sure how to handle it now, and would not want to delay the release for this (since it has been discussed quite a bit in the past). Seeing an evaluation or two for these requirements could provide a better way forward for this (not to mention the ISO work may provide a means for better handling of optional threats).

**Comment by n-kai** [comment]
The following threat (**T.Presentation_Attack**) was defined in the previous version of the cPP but we agreed to remove this because one CC certification body insisted that the any TOE can't resist the presentation attacks even from attackers who possess basic attack potential. I am not sure whether they are right or not but removing the T.Presentation_Attack and making the PAD optional was the only solution to avoid conflicts or problems during CCDB/CCMB reviews or endorsement of our cPP. So I am reluctant to bring **T.Presentation_Attack** back into the cPP and have the same discussion again with certification bodies.

**T.Presentation_Attack**
_An attacker may attempt a presentation attack to the TOE. In order to perform the attack, the attacker uses artificial Presentation Attack Instrument (PAI) except his/her own biometric characteristic._

**Comment by gfiumara** [comment]
I'd agree with @woodbe that the casual, zero-effort, pick-up-a-lost-phone-and-unlock attack is about all you can do without the optional presentation attack detection portion. Twins in a face unlock scenario might suffer from the casual attack, but this is otherwise a test of the FAR of the matching algorithm. An "intentional attack" is testing both PAD and FAR.

**Comment by woodbe** [comment]
Closing based on discussion on 5/7 call.
