### ISSUE TITLE
[NIAP] FIA_MBV_EXT.1.2 application notes

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#306]
Section 8.2.3, FIA_MBV_EXT.1.2, application note 14: This may be more of a endorsement statement thing, but it seems that the ST author is free to put anything they want into the assignments that essentially deal with how well the TOE works. This is not desirable from a "service-to-our-users" perspective. If two TOEs have a certificate and one TOE complies with NIST recommendations on values and the other does not, do we really expect the user to read in the ST to find these values and then make a determination of goodness? The goal for PPs is setting a clear minimum bar that the community believes is both achievable and provides some value to the end user.

Section 8.2.3, FIA_MBV_EXT.1.2, application note 14, item c: This item has the general problem mentioned earlier of containing "shall" statements even though 1) it's in an application note and 2) the introductory text in the application note says "...the ST author should consider..."

The more important issue is that this item uses the term "target error rates", but that is not defined in the glossary (nor anywhere else in the PP-Module), nor is it defined in the SD. It's unclear what this means, especially when the last sentence says that the SD describes how to objectively evaluate these things that aren't defined anywhere (and in fact, the SD does not do this).

**Comment by woodbe** [comment]
So the simplest answer off hand is to provide an upper boundary on the acceptable criteria (this is what NIAP has done). I set the values to 1:1000 FAR and 10% FRR as these should be "easy" to meet and shouldn't cause any problems, but do set a minimum.

By comparison, FIDO is now requiring 1:10000 and 5% (though I thought it was supposed to be 7%, it may be that there are some cases where 7% is acceptable, I would have to dig into it more to be certain).

I think the point about "target error rate" is them misreading it. It is really the "targeted" error rates. I just removed the "target" as I thought this was easiest, but the term shouldn't need to be defined as the target is a descriptor of the error rate, not a specific type of error rate.

**Comment by gfiumara** [comment]
1. Did we define a minimum number of subjects somewhere? Let's be sure that measuring FMR @ 1:1000/1:10000 aligns statistically with this.
2. FNMR < 10% is table stakes at this point. I'd at least match FIDO in this respect.

**Comment by woodbe** [comment]
@n-kai will review the SP800-63 draft document and provide some further comments/updates regarding the final FAR/FRR values.

1:10K seems good, but not certain at this point (NIST seems to be pointing in this direction, but isn't finalized yet). FRR below 10% would be preferred, the question would be how low, 5% vs 7%.

**Comment by n-kai** [comment]
I checked relevant standards that define upper boundary of acceptable biometric performance (I am also checking the latest ISO SC37 standards but I believe that ISO standards don't specify such boundary). I will propose the minimum error rates (i.e. FAR/FRR and FMR/FNMR) that can meet all those standards or guidance by the next meeting (18th May). If I can't find any guidance in the ISO standards, the following could be the minimum error rates to be specified in FIA_MBV_EXT.1.2. 

_False Reject Rate SHALL meet the requirement of less than 5:100 for the upper bound of a 80% confidence interval. FRR is measured at the verification transaction level._

_MUST have a false acceptance rate less than 0.002% (or 1/50k)_

Current BIOSD requires to measure FAR/FMR following rule of 3 and developer needs at least 275 test subjects to achieve 1/50k FAR if two samples are corrected from single test subject (e.g. two fingerprints or two eyes) 

BIOSD doesn't require the rule of 3 to measure FRR/FNMR because developer needs tens of thousands of test subjects if developer specifies quite low FRR/FNMR in FIA_MBV_EXT.1.2.     

**NIST SP 800-63-B** *1)
_The biometric system SHALL operate with an FMR of 1 in 1000 or better. This FMR SHALL be achieved under conditions of a conformant attack (i.e., zero-effort impostor attempt) as defined in ISO/IEC 30107-1._

**FIDO Biometrics Requirements** *2)
_False Reject Rate SHALL meet the requirement of less than 5:100 for the upper bound of a 80% confidence interval. FRR is measured at the verification transaction level._

_False Accept Rate SHALL meet the requirement of less than 1:10,000 for the upper bound of a 80% confidence interval. FAR is measured at the transaction level._

**Android 10 Compatibility Definitiony** *3)
_MUST have a false acceptance rate less than 0.002% (or 1/50k)_

_Are STRONGLY RECOMMENDED to have a false rejection rate of less than 10%, as measured on the device._ 

*1) https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf
*2) https://fidoalliance.org/specs/biometric/requirements/#FRRReq
*3) https://source.android.com/compatibility/10/android-10-cdd

"target error rates" is the term used by Japanese vendors who develop biometrics products for border control or ATMs, not for mobile devices. Requirement for error rates (minimum FAR and FRR that vendor has to meet) normally come from customers like bank and vendors need to achieve those "target" value to follow customer's requirement in any case. But if mobile biometrics don't follow the similar development style, we have to change or remove this "target".

**Comment by gfiumara** [comment]
Note: NIST internal pre-release draft/discussion of 800-63B says, "FMR of 1 in 10000 or better."

**Comment by woodbe** [comment]
NIAP may come back with a different answer later (based on further input), but at this point they like the 1:10K value and I expect they will stick to that for the minimum number as NIST is saying. So I think we are safe going with 1:10K or higher.

**Comment by n-kai** [comment]
What about confidence level? If we select 1:10K (0.01%) for FAR/FMR and follow rule of 3 (95% confidence level), vendor needs 174 test subjects if cross-comparison of ordered pairs (i.e. cross match both (A's finger template - B's finger sample) and (B's finger template - A's finger sample)) is allowed or 246 test subjects if not allowed, and all imposter transactions/attempts must fail to achieve FAR/FMR less than 0.01%.

I want to know the minimum number for FRR/FNMR and confidence level. Normally we see some failed genuine transactions or attempts so we can't use the rule of 3 for FRR/FNMR.

Current SD requires to follow rule of 3 for FAR/FMR but don't require this rule of 3 (or rule of 30) for FRR/FNMR to limit the max number of test subjects.

I checked the SC 37 ISO standards (19795-1 and 19795-9) but both docs don't specify minimum number.

**Comment by woodbe** [comment]
Well FIDO went with an 80% confidence interval. I didn't actually ask NIAP on that question (I'll send it now), but I think 80% is a more realistic number in terms of performing evaluations within a reasonable time/cost.

**Comment by n-kai** [comment]
Thank you, I will update PPM and SD based on the response from NIAP.

**Comment by woodbe** [comment]
@n-kai after speaking with NIAP and NIST today, here is a summary:

- 1:10K minimum is good for now, but would like to know about higher (as time goes on or as industry is ready)
- 80% confidence interval is acceptable at this time (and likely going forward), with the expectation that the minimum FAR value is likely to increase, and keeping the confidence interval the same has some benefits. Also, it would be better to not require vendors to keep re-evaluating the same thing for many different standards, so if this seems to be good for industry at this point, it is good now
- FRR should be a table of acceptable values based on the modality. For example face tends to have a very low FRR, while small sensor size fingerprint sensors are higher. Instead of allowing face to use the fingerprint value, they should be adjusted accordingly.
  - The values will need to be determined, and the requirement edited to point to the table as a selection based on the modality (or more) chosen.

**Comment by n-kai** [comment]
@woodbe 

**80% confidence interval** 
As explained in #331, DEA require 95% confidence and iBeta (*1) follow this confidence level to estimate the FMR. So if we want to maximize the value of CC certificate, we should take 95% confidence. But I don't know what DEA requirements mean to mobile vendors. If it's not so important to mobile vendors, 80% is fine for me.

 **FRR**
If the number of participants is 245,  245 * FRR should be more than 10 (See page 52 of *1)) to estimate upper bound of confidence interval. This means FRR should be greater than 5% or 5:100 (number of false rejection should be equal or less than 8 if we run 245 genuine transactions and take 80% confidence interval). This 5% meet the FIDO requirement (False Reject Rate SHALL meet the requirement of less than 5:100 for the upper bound of a 80% confidence interval. FRR is measured at the verification transaction level) so we can take this 5% for minimum FRR for all modality, rather than defining separate value for each modality. 
 

*1) National Biometric Test Center Collected Works (https://www.researchgate.net/publication/246920937_National_Biometric_Test_Center_Collected_Works)

**Comment by woodbe** [comment]
@n-kai is there a reason to use 80% CI for FRR and 95% for FAR? I would have thought you would want both of those to be the same (but statistics is certainly not my forte).

**Comment by n-kai** [comment]
@woodbe 

**FAR**
- FAR is related to security issues so customers asks vendor to measure it with high confidence (i.e. 95 CI) like DEA.
- I believe that vendors don't see any false acceptance with 200 or 300 participants (and should not observe any false acceptance with a few hundreds of test subject). This means that vendors have to follow the rule of 3 (i.e. 95% confidence interval).

**FRR**
-  FRR is not related to security but related to usability so it may be acceptable to measure it with lower confidence for security evaluation. 
- FRR may vary depending on environment condition or participant demographics. For example, if vendor's participants include those people who have never used mobile device before (e.g. elderly people), they may see much higher number of false reject errors even they spend enough time for training and FRR may increase two or threefold (however vendor normally doesn't include such participants). So both FRR estimated with 80% CI and one with 95% CI may not be applicable to customer's operational environment.

But we should be flexible to cover variety of requirement including FIDO requirement so our PPM can define following requirements.

**FAR SHALL meet the requirement of less than [assignment: value equal to or less than 1:10K] for the upper bound of a [assignment: value equal to or greater than 80%] confidence interval**

**FRR SHALL meet the requirement of less than [assignment: value equal to or less than 5:100] for the upper bound of a [assignment: value equal to or greater than 80%] confidence interval**

**Comment by woodbe** [comment]
the proposal from @n-kai about the FAR and FRR was agreed to on the 6/1 call
