### ISSUE TITLE
[NIAP] FPT_BDP_EXT.* SEE assurance activities

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#308]
Section 8.3, FPT_BDP_EXT.x: These requirements are written with respect to a Security Execution Environment. Since this is a PP-Module, there should be some verification that the Base PP requires a Security
Execution Environment--in this way, the assurance activities can be written in a more objective way.

**Comment by woodbe** [comment]
I propose that the FPT_BDP_EXT.2 and FPT_BDP_EXT.3 be removed, and in their place, the MDF requirements FPT_KST_EXT.1 and FPT_KST_EXT.2, respectively, be marked in the PPM as expanded to cover biometric data in the combined TOE. Currently these SFRs in the v3.1/3.2 docs do this (basically if a BAF is used, then these also cover biometric data). These would be added to a "Modified SFRs" section for the MDFPP with edits to the application note (and if needed the EA) but no changes to the requirements directly (since they are pretty simple).

This will simplify the requirements, though it may mean combining with the GP OS may require further updates (though these could be specifically added back in that case under the GP integration).

**Comment by n-kai** [comment]
@woodbe 
I basically agree with you. I also think that we should update our PPM following the format of latest NIAP PP module that is "PP-Module for VPN Client, Version 2.2"
According to this PPM, "Modified SFR" are those SFR that ST author needs to complete selections and/or assignments in a specific manner in order to ensure that the functionality provided by the mobile device is consistent with the functionality required by the biometric systems. However both FPT_KST_EXT.1 and FPT_KST_EXT.2 don't provide any selections or assignment for including biometric data. So we should;

- replace "plaintext key material" in FPT_KST_EXT.1 and FPT_KST_EXT.2 with "plaintext biometric data" and add them to "Additional SFRs"
or 
- ask NIAP to add assignment to FPT_KST_EXT.1 and FPT_KST_EXT.2 so that ST author can assign "plaintext biometric data" and add them to "Modified SFR"  

But I don't know which is better.

**Comment by woodbe** [comment]
@n-kai So we could copy them (iterate them) into our PP-Module and do the replacement for the first point. I'm inclined though to modify them to just include biometric data. Currently that is written into the notes, but we could make it explicit, and this should be simple and agreeable.
