### ISSUE TITLE
Supporting Document v1.1 Section 11.2.1

### ISSUE THREAD

**Issue by xahun** [biometricITC/cPP-biometrics#377]
Supporting Document v1.1 Section 11.2.1 "The evaluator shall select one week at maximum"...  Does it matter how many TOE devices are being tested?  I assume one week means one person week (i.e., 40 hours) of effort, and maybe that should be clarified.  But the statement should also clarify how multiple test devices might affect the time frame.

**Comment by n-kai** [comment]
"shall" in "The evaluator shall select one..." should be replaced with "should". The reason why this sentence was added is that some iTC members claimed that upper bond of time and effort for testing should be defined in the SD. But SD should not enforce such limit instead SD should show general agreement so that evaluator and developer can share the common understanding about the workload of testing.

**Comment by woodbe** [comment]
In addition to the "should" change, add some sort of note that this one week is for a single "sensor" and that testing for multiple sensors/devices does not mean that each one must take a week (parallel testing, reuse of species, etc). So that the evaluator needs to provide enough information about the level of effort to justify the week timeframe.
