### ISSUE TITLE
usage of FIA_ATD.1/User attribute definition

### ISSUE THREAD

**Issue by FGUERINGTO** [biometricITC/cPP-biometrics#96]
I suggest to add a SFR to handle the security attribute Verification outcome.
FIA_ATD.1/BD User attribute definition
FIA_ATD.1.1/BD The TSF shall maintain the following list of security attributes belonging to individual   users: [assignment: Verification outcome, decision threshold].

Application note : as defined on figure 1, 
Verification outcome is reset at begin of verification operation and it has to be updated as the result of operation performed by decision subsystem,
Decision threshold is an input for the TOE, allowing an accurate verdict

**Comment by woodbe** [comment]
I'm suggesting we close this. 

I am not sure why we would need to store the outcome as a security attribute nor why we would want to maintain the outcome information beyond say an audit record. We have audit being listed for PAD (i.e. if a PAD is detected it should be noted) along with the outcome (pass/fail), but I'm not sure there is much value, in mobile devices, of a threshold value being noted since this is generally something the vendor fixes (and doesn't allow to be changed), and it is universal, so I am unclear as to the intent.

**Comment by n-kai** [comment]
I also agree to close this.

**Comment by nils-tekampe** [comment]
i agree

**Comment by woodbe** [comment]
Closed based on agreement.
